Repository Soviet-Linux/libspm, pull requests merged in 2023-12, with the labels that each got.

#35 bruh
  src/exec.c
Labels: size/XS

#38 changes
  include/libspm.h
  src/move.c
Labels: size/M

#37 Create .gitmodules
  .gitmodules
Labels: size/XS

#39 ...
  include/libspm.h
  src/link.c
  src/move.c
Labels: size/L

#40 Rewriting the link function to be more readable
  src/install.c
  src/link.c
  src/move.c
Labels: size/L

#41 added more error checking to mvsp
  lib/cutils.a
  src/link.c
  src/move.c
Labels: size/L

#42 Fix format-security warning in link.c
  src/link.c
Labels: size/XS

#43 Add support for $DESTDIR
  makefile
Labels: size/XS
