Repository Soviet-Linux/libspm, pull requests merged in 2023-10, with the labels that each got.

#4 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#5 updated some files
  src/download.c
  src/init.c
  src/install.c
  src/pkg.c
Labels: size/S

#6 Delete dev/cccp.c
  dev/cccp.c
Labels: size/L

#7 Added comments
  makefile
  src/check.c
  src/clean.c
  src/config.c
  src/create.c
  src/data.c
  src/deps.c
  src/download.c
  src/exec.c
  src/get.c
  src/globals.c
  src/init.c
  src/install.c
  src/locations.c
  src/make.c
  src/move.c
  src/pkg.c
  src/quit.c
  src/remove.c
  src/uninstall.c
  src/version.c
Labels: size/XXL

#8 remove unnessesary line in makefile
  README.md
  makefile
Labels: size/XS

#9 fix install.c
  src/install.c
Labels: size/XS

#11 libspm.h comments
  docs/docs.md
  docs/new-format.md
  include/libspm.h
Labels: size/L

#12 fix deps.c
  src/deps.c
Labels: size/XS

#13 Added default values incase CCCP.conf doesnt exist
  dev/vim.ecmp
  src/config.c
  src/data.c
  src/get.c
  src/init.c
  src/uninstall.c
Labels: size/L

#14 debug
  dev/test.c
Labels: size/XS

#17 Add clang-format and clang-tidy configs
  .clang-format
  .clang-tidy
Labels: size/L

#15 debug
  dev/test.c
Labels: size/S

#18 Add automatic formatting and linting
  .github/workflows/c-lint.yml
Labels: size/S

#19 Make some nums unsigned to reduce compiler warnings when compiling fo…
  formats/ecmp/ecmp.c
  include/cutils.h
Labels: size/S

#20 Better arguments and checks for spm-test
  .github/workflows/c-cpp.yml
  dev/test.c
  dev/vim.mod.ecmp
Labels: size/M

#22 Update config.c
  src/config.c
Labels: size/XS

#23 basic changes
  src/globals.c
  src/init.c
Labels: size/XS

#24 fixed uninstall
  src/uninstall.c
Labels: size/XS

#25 added mock implementations for listing installed files
  include/libspm.h
  src/list.c
Labels: size/M
