Repository Soviet-Linux/libspm, pull requests merged in 2023-11, with the labels that each got.

#26 fixed some environment variables variating between comfig.c and init.c
  src/config.c
  src/init.c
  src/list.c
  src/move.c
Labels: size/M

#27 added list, update and upgrade
  include/libspm.h
  src/get.c
  src/list.c
  src/update.c
Labels: size/L

#28 added basic search implementacion
  include/libspm.h
  src/list.c
Labels: size/M

#30 A bunch of fixes to silence the compiler warnings
  src/data.c
  src/list.c
  src/update.c
Labels: size/M

#31 Added spm-test instructions
  README.md
Labels: size/XS

#32 Update README.md with memory debuggin intructions
  README.md
Labels: size/XS

#33 less annoying
  src/update.c
Labels: size/XS

#34 fixed stuff
  src/deps.c
  src/move.c
Labels: size/XS
