Repository Soviet-Linux/libspm, pull requests merged in 2024-05, with the labels that each got.

#72 fixed linking
  src/link.c
Labels: size/L

#73 Common rewrite
  src/link.c
Labels: size/S

#74 Common rewrite
  include/cutils.h
  lib/cutils.a
  src/install.c
  src/link.c
  src/locations.c
  src/make.c
  src/move.c
Labels: size/L

#75 IT WORKS
  makefile
  src/get.c
  src/make.c
Labels: size/M

#76 Common rewrite
  src/config.c
  src/get.c
Labels: size/S

#77 Common rewrite
  src/move.c
Labels: size/XS
