Repository Soviet-Linux/libspm, pull requests merged in 2024-07, with the labels that each got.

#96 stuff i forgot in the last PR (not very important)
  .github/workflows/c-cpp.yml
  dev/test.c
  dev/vim.ecmp.mod
Labels: size/L

#93 made it retry downloads
  src/make.c
Labels: size/L

#94 moved the variable assigment out of make
  formats/ecmp/ecmp.c
  include/libspm.h
  src/config.c
  src/deps.c
  src/download.c
  src/get.c
  src/init.c
  src/install.c
  src/make.c
  src/move.c
  test/test.c
Labels: size/XL

#99 added retry to file downloads
  src/make.c
Labels: size/XS

#98 added an config variable for extra dirs to clean up
  src/clean.c
  src/config.c
Labels: size/M

#101 Moving hashtable to Cutils
  src/clean.c
  src/config.c
  src/make.c
Labels: size/M
