Repository Soviet-Linux/libspm, pull requests merged in 2024-10, with the labels that each got.

#116 Fixed some memory issues
  src/environment.c
  src/make.c
  src/update.c
Labels: size/M

#114 Git rework
  .github/workflows/c-cpp.yml
  include/libspm.h
  makefile
  src/get.c
  src/init.c
Labels: size/L

#118 Fix for redundant warning
  include/libspm.h
  src/clean.c
  src/install.c
Labels: size/M

#119 Update ecmp.c
  formats/ecmp/ecmp.c
Labels: size/XS

#120 Fixing New Warnings.
  src/download.c
  src/make.c
Labels: size/S
